services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  web:
    build: ./apps/web
    container_name: web
    ports:
      - "3000:3000"
    depends_on:
      - kafka

  worker:
    build: ./apps/worker
    container_name: worker
    depends_on:
      - kafka
      - web
    scale: 3

  consumer:
    build: ./apps/consumer
    container_name: consumer
    depends_on:
      - kafka
      - web
      - worker
